//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LOJASenai", "FK_PRODUTO_CATEGORIA", "CATEGORIA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.CATEGORIA), "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.PRODUTO), true)]
[assembly: EdmRelationshipAttribute("LOJASenai", "FK_COMENTARIO_PRODUTO", "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.PRODUTO), "COMENTARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.COMENTARIO), true)]
[assembly: EdmRelationshipAttribute("LOJASenai", "FK_PRODUTO_FABRICANTE", "FABRICANTE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.FABRICANTE), "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.PRODUTO), true)]
[assembly: EdmRelationshipAttribute("LOJASenai", "FK_ITEM_VENDA_PRODUTO", "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.PRODUTO), "ITEM_VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.ITEM_VENDA), true)]
[assembly: EdmRelationshipAttribute("LOJASenai", "FK_VENDA_CLIENTE", "CLIENTE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.CLIENTE), "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.VENDA), true)]
[assembly: EdmRelationshipAttribute("LOJASenai", "FK_ITEM_VENDA_VENDA", "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.VENDA), "ITEM_VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.ITEM_VENDA), true)]
[assembly: EdmRelationshipAttribute("LOJASenai", "FK_VENDA_TIPO_VENDA", "TIPO_VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ecommerce.DAO.TIPO_VENDA), "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ecommerce.DAO.VENDA), true)]

#endregion

namespace Ecommerce.DAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LojaVirtual : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LojaVirtual object using the connection string found in the 'LojaVirtual' section of the application configuration file.
        /// </summary>
        public LojaVirtual() : base("name=LojaVirtual", "LojaVirtual")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LojaVirtual object.
        /// </summary>
        public LojaVirtual(string connectionString) : base(connectionString, "LojaVirtual")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LojaVirtual object.
        /// </summary>
        public LojaVirtual(EntityConnection connection) : base(connection, "LojaVirtual")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BANNER> BANNER
        {
            get
            {
                if ((_BANNER == null))
                {
                    _BANNER = base.CreateObjectSet<BANNER>("BANNER");
                }
                return _BANNER;
            }
        }
        private ObjectSet<BANNER> _BANNER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CATEGORIA> CATEGORIA
        {
            get
            {
                if ((_CATEGORIA == null))
                {
                    _CATEGORIA = base.CreateObjectSet<CATEGORIA>("CATEGORIA");
                }
                return _CATEGORIA;
            }
        }
        private ObjectSet<CATEGORIA> _CATEGORIA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLIENTE> CLIENTE
        {
            get
            {
                if ((_CLIENTE == null))
                {
                    _CLIENTE = base.CreateObjectSet<CLIENTE>("CLIENTE");
                }
                return _CLIENTE;
            }
        }
        private ObjectSet<CLIENTE> _CLIENTE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COMENTARIO> COMENTARIO
        {
            get
            {
                if ((_COMENTARIO == null))
                {
                    _COMENTARIO = base.CreateObjectSet<COMENTARIO>("COMENTARIO");
                }
                return _COMENTARIO;
            }
        }
        private ObjectSet<COMENTARIO> _COMENTARIO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FABRICANTE> FABRICANTE
        {
            get
            {
                if ((_FABRICANTE == null))
                {
                    _FABRICANTE = base.CreateObjectSet<FABRICANTE>("FABRICANTE");
                }
                return _FABRICANTE;
            }
        }
        private ObjectSet<FABRICANTE> _FABRICANTE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ITEM_VENDA> ITEM_VENDA
        {
            get
            {
                if ((_ITEM_VENDA == null))
                {
                    _ITEM_VENDA = base.CreateObjectSet<ITEM_VENDA>("ITEM_VENDA");
                }
                return _ITEM_VENDA;
            }
        }
        private ObjectSet<ITEM_VENDA> _ITEM_VENDA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PRODUTO> PRODUTO
        {
            get
            {
                if ((_PRODUTO == null))
                {
                    _PRODUTO = base.CreateObjectSet<PRODUTO>("PRODUTO");
                }
                return _PRODUTO;
            }
        }
        private ObjectSet<PRODUTO> _PRODUTO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TIPO_VENDA> TIPO_VENDA
        {
            get
            {
                if ((_TIPO_VENDA == null))
                {
                    _TIPO_VENDA = base.CreateObjectSet<TIPO_VENDA>("TIPO_VENDA");
                }
                return _TIPO_VENDA;
            }
        }
        private ObjectSet<TIPO_VENDA> _TIPO_VENDA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VENDA> VENDA
        {
            get
            {
                if ((_VENDA == null))
                {
                    _VENDA = base.CreateObjectSet<VENDA>("VENDA");
                }
                return _VENDA;
            }
        }
        private ObjectSet<VENDA> _VENDA;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BANNER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBANNER(BANNER bANNER)
        {
            base.AddObject("BANNER", bANNER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CATEGORIA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCATEGORIA(CATEGORIA cATEGORIA)
        {
            base.AddObject("CATEGORIA", cATEGORIA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLIENTE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLIENTE(CLIENTE cLIENTE)
        {
            base.AddObject("CLIENTE", cLIENTE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COMENTARIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOMENTARIO(COMENTARIO cOMENTARIO)
        {
            base.AddObject("COMENTARIO", cOMENTARIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FABRICANTE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFABRICANTE(FABRICANTE fABRICANTE)
        {
            base.AddObject("FABRICANTE", fABRICANTE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ITEM_VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToITEM_VENDA(ITEM_VENDA iTEM_VENDA)
        {
            base.AddObject("ITEM_VENDA", iTEM_VENDA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PRODUTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPRODUTO(PRODUTO pRODUTO)
        {
            base.AddObject("PRODUTO", pRODUTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TIPO_VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTIPO_VENDA(TIPO_VENDA tIPO_VENDA)
        {
            base.AddObject("TIPO_VENDA", tIPO_VENDA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVENDA(VENDA vENDA)
        {
            base.AddObject("VENDA", vENDA);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="BANNER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BANNER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BANNER object.
        /// </summary>
        /// <param name="iDT_BANNER">Initial value of the IDT_BANNER property.</param>
        /// <param name="imageUrl">Initial value of the ImageUrl property.</param>
        /// <param name="navigateUrl">Initial value of the NavigateUrl property.</param>
        /// <param name="alternateText">Initial value of the AlternateText property.</param>
        /// <param name="impressions">Initial value of the Impressions property.</param>
        public static BANNER CreateBANNER(global::System.Int32 iDT_BANNER, global::System.String imageUrl, global::System.String navigateUrl, global::System.String alternateText, global::System.Int32 impressions)
        {
            BANNER bANNER = new BANNER();
            bANNER.IDT_BANNER = iDT_BANNER;
            bANNER.ImageUrl = imageUrl;
            bANNER.NavigateUrl = navigateUrl;
            bANNER.AlternateText = alternateText;
            bANNER.Impressions = impressions;
            return bANNER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_BANNER
        {
            get
            {
                return _IDT_BANNER;
            }
            set
            {
                if (_IDT_BANNER != value)
                {
                    OnIDT_BANNERChanging(value);
                    ReportPropertyChanging("IDT_BANNER");
                    _IDT_BANNER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_BANNER");
                    OnIDT_BANNERChanged();
                }
            }
        }
        private global::System.Int32 _IDT_BANNER;
        partial void OnIDT_BANNERChanging(global::System.Int32 value);
        partial void OnIDT_BANNERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NavigateUrl
        {
            get
            {
                return _NavigateUrl;
            }
            set
            {
                OnNavigateUrlChanging(value);
                ReportPropertyChanging("NavigateUrl");
                _NavigateUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NavigateUrl");
                OnNavigateUrlChanged();
            }
        }
        private global::System.String _NavigateUrl;
        partial void OnNavigateUrlChanging(global::System.String value);
        partial void OnNavigateUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlternateText
        {
            get
            {
                return _AlternateText;
            }
            set
            {
                OnAlternateTextChanging(value);
                ReportPropertyChanging("AlternateText");
                _AlternateText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AlternateText");
                OnAlternateTextChanged();
            }
        }
        private global::System.String _AlternateText;
        partial void OnAlternateTextChanging(global::System.String value);
        partial void OnAlternateTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Impressions
        {
            get
            {
                return _Impressions;
            }
            set
            {
                OnImpressionsChanging(value);
                ReportPropertyChanging("Impressions");
                _Impressions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Impressions");
                OnImpressionsChanged();
            }
        }
        private global::System.Int32 _Impressions;
        partial void OnImpressionsChanging(global::System.Int32 value);
        partial void OnImpressionsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="CATEGORIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CATEGORIA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CATEGORIA object.
        /// </summary>
        /// <param name="iDT_CATEGORIA">Initial value of the IDT_CATEGORIA property.</param>
        public static CATEGORIA CreateCATEGORIA(global::System.Int32 iDT_CATEGORIA)
        {
            CATEGORIA cATEGORIA = new CATEGORIA();
            cATEGORIA.IDT_CATEGORIA = iDT_CATEGORIA;
            return cATEGORIA;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_CATEGORIA
        {
            get
            {
                return _IDT_CATEGORIA;
            }
            set
            {
                if (_IDT_CATEGORIA != value)
                {
                    OnIDT_CATEGORIAChanging(value);
                    ReportPropertyChanging("IDT_CATEGORIA");
                    _IDT_CATEGORIA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_CATEGORIA");
                    OnIDT_CATEGORIAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_CATEGORIA;
        partial void OnIDT_CATEGORIAChanging(global::System.Int32 value);
        partial void OnIDT_CATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_PRODUTO_CATEGORIA", "PRODUTO")]
        public EntityCollection<PRODUTO> PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PRODUTO>("LOJASenai.FK_PRODUTO_CATEGORIA", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PRODUTO>("LOJASenai.FK_PRODUTO_CATEGORIA", "PRODUTO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="CLIENTE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENTE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLIENTE object.
        /// </summary>
        /// <param name="iDT_CLIENTE">Initial value of the IDT_CLIENTE property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        /// <param name="sENHA">Initial value of the SENHA property.</param>
        /// <param name="dATA_CADASTRO">Initial value of the DATA_CADASTRO property.</param>
        public static CLIENTE CreateCLIENTE(global::System.Int32 iDT_CLIENTE, global::System.String nOME, global::System.String eMAIL, global::System.String sENHA, global::System.DateTime dATA_CADASTRO)
        {
            CLIENTE cLIENTE = new CLIENTE();
            cLIENTE.IDT_CLIENTE = iDT_CLIENTE;
            cLIENTE.NOME = nOME;
            cLIENTE.EMAIL = eMAIL;
            cLIENTE.SENHA = sENHA;
            cLIENTE.DATA_CADASTRO = dATA_CADASTRO;
            return cLIENTE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_CLIENTE
        {
            get
            {
                return _IDT_CLIENTE;
            }
            set
            {
                if (_IDT_CLIENTE != value)
                {
                    OnIDT_CLIENTEChanging(value);
                    ReportPropertyChanging("IDT_CLIENTE");
                    _IDT_CLIENTE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_CLIENTE");
                    OnIDT_CLIENTEChanged();
                }
            }
        }
        private global::System.Int32 _IDT_CLIENTE;
        partial void OnIDT_CLIENTEChanging(global::System.Int32 value);
        partial void OnIDT_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SENHA
        {
            get
            {
                return _SENHA;
            }
            set
            {
                OnSENHAChanging(value);
                ReportPropertyChanging("SENHA");
                _SENHA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SENHA");
                OnSENHAChanged();
            }
        }
        private global::System.String _SENHA;
        partial void OnSENHAChanging(global::System.String value);
        partial void OnSENHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATA_CADASTRO
        {
            get
            {
                return _DATA_CADASTRO;
            }
            set
            {
                OnDATA_CADASTROChanging(value);
                ReportPropertyChanging("DATA_CADASTRO");
                _DATA_CADASTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA_CADASTRO");
                OnDATA_CADASTROChanged();
            }
        }
        private global::System.DateTime _DATA_CADASTRO;
        partial void OnDATA_CADASTROChanging(global::System.DateTime value);
        partial void OnDATA_CADASTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONE
        {
            get
            {
                return _TELEFONE;
            }
            set
            {
                OnTELEFONEChanging(value);
                ReportPropertyChanging("TELEFONE");
                _TELEFONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONE");
                OnTELEFONEChanged();
            }
        }
        private global::System.String _TELEFONE;
        partial void OnTELEFONEChanging(global::System.String value);
        partial void OnTELEFONEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_VENDA_CLIENTE", "VENDA")]
        public EntityCollection<VENDA> VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VENDA>("LOJASenai.FK_VENDA_CLIENTE", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VENDA>("LOJASenai.FK_VENDA_CLIENTE", "VENDA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="COMENTARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COMENTARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COMENTARIO object.
        /// </summary>
        /// <param name="iDT_COMENTARIO">Initial value of the IDT_COMENTARIO property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        /// <param name="dESCRICAO">Initial value of the DESCRICAO property.</param>
        /// <param name="iDT_PRODUTO">Initial value of the IDT_PRODUTO property.</param>
        /// <param name="nOTA">Initial value of the NOTA property.</param>
        public static COMENTARIO CreateCOMENTARIO(global::System.Int32 iDT_COMENTARIO, global::System.String nOME, global::System.String eMAIL, global::System.String dESCRICAO, global::System.Int32 iDT_PRODUTO, global::System.Int32 nOTA)
        {
            COMENTARIO cOMENTARIO = new COMENTARIO();
            cOMENTARIO.IDT_COMENTARIO = iDT_COMENTARIO;
            cOMENTARIO.NOME = nOME;
            cOMENTARIO.EMAIL = eMAIL;
            cOMENTARIO.DESCRICAO = dESCRICAO;
            cOMENTARIO.IDT_PRODUTO = iDT_PRODUTO;
            cOMENTARIO.NOTA = nOTA;
            return cOMENTARIO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_COMENTARIO
        {
            get
            {
                return _IDT_COMENTARIO;
            }
            set
            {
                if (_IDT_COMENTARIO != value)
                {
                    OnIDT_COMENTARIOChanging(value);
                    ReportPropertyChanging("IDT_COMENTARIO");
                    _IDT_COMENTARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_COMENTARIO");
                    OnIDT_COMENTARIOChanged();
                }
            }
        }
        private global::System.Int32 _IDT_COMENTARIO;
        partial void OnIDT_COMENTARIOChanging(global::System.Int32 value);
        partial void OnIDT_COMENTARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_PRODUTO
        {
            get
            {
                return _IDT_PRODUTO;
            }
            set
            {
                OnIDT_PRODUTOChanging(value);
                ReportPropertyChanging("IDT_PRODUTO");
                _IDT_PRODUTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_PRODUTO");
                OnIDT_PRODUTOChanged();
            }
        }
        private global::System.Int32 _IDT_PRODUTO;
        partial void OnIDT_PRODUTOChanging(global::System.Int32 value);
        partial void OnIDT_PRODUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NOTA
        {
            get
            {
                return _NOTA;
            }
            set
            {
                OnNOTAChanging(value);
                ReportPropertyChanging("NOTA");
                _NOTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NOTA");
                OnNOTAChanged();
            }
        }
        private global::System.Int32 _NOTA;
        partial void OnNOTAChanging(global::System.Int32 value);
        partial void OnNOTAChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_COMENTARIO_PRODUTO", "PRODUTO")]
        public PRODUTO PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJASenai.FK_COMENTARIO_PRODUTO", "PRODUTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJASenai.FK_COMENTARIO_PRODUTO", "PRODUTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUTO> PRODUTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJASenai.FK_COMENTARIO_PRODUTO", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUTO>("LOJASenai.FK_COMENTARIO_PRODUTO", "PRODUTO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="FABRICANTE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FABRICANTE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FABRICANTE object.
        /// </summary>
        /// <param name="iDT_FABRICANTE">Initial value of the IDT_FABRICANTE property.</param>
        public static FABRICANTE CreateFABRICANTE(global::System.Int32 iDT_FABRICANTE)
        {
            FABRICANTE fABRICANTE = new FABRICANTE();
            fABRICANTE.IDT_FABRICANTE = iDT_FABRICANTE;
            return fABRICANTE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_FABRICANTE
        {
            get
            {
                return _IDT_FABRICANTE;
            }
            set
            {
                if (_IDT_FABRICANTE != value)
                {
                    OnIDT_FABRICANTEChanging(value);
                    ReportPropertyChanging("IDT_FABRICANTE");
                    _IDT_FABRICANTE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_FABRICANTE");
                    OnIDT_FABRICANTEChanged();
                }
            }
        }
        private global::System.Int32 _IDT_FABRICANTE;
        partial void OnIDT_FABRICANTEChanging(global::System.Int32 value);
        partial void OnIDT_FABRICANTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_PRODUTO_FABRICANTE", "PRODUTO")]
        public EntityCollection<PRODUTO> PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PRODUTO>("LOJASenai.FK_PRODUTO_FABRICANTE", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PRODUTO>("LOJASenai.FK_PRODUTO_FABRICANTE", "PRODUTO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="ITEM_VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ITEM_VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ITEM_VENDA object.
        /// </summary>
        /// <param name="iDT_VENDA">Initial value of the IDT_VENDA property.</param>
        /// <param name="iDT_PRODUTO">Initial value of the IDT_PRODUTO property.</param>
        /// <param name="qUANTIDADE">Initial value of the QUANTIDADE property.</param>
        /// <param name="vALOR_UNITARIO">Initial value of the VALOR_UNITARIO property.</param>
        public static ITEM_VENDA CreateITEM_VENDA(global::System.Int32 iDT_VENDA, global::System.Int32 iDT_PRODUTO, global::System.Int32 qUANTIDADE, global::System.Decimal vALOR_UNITARIO)
        {
            ITEM_VENDA iTEM_VENDA = new ITEM_VENDA();
            iTEM_VENDA.IDT_VENDA = iDT_VENDA;
            iTEM_VENDA.IDT_PRODUTO = iDT_PRODUTO;
            iTEM_VENDA.QUANTIDADE = qUANTIDADE;
            iTEM_VENDA.VALOR_UNITARIO = vALOR_UNITARIO;
            return iTEM_VENDA;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_VENDA
        {
            get
            {
                return _IDT_VENDA;
            }
            set
            {
                if (_IDT_VENDA != value)
                {
                    OnIDT_VENDAChanging(value);
                    ReportPropertyChanging("IDT_VENDA");
                    _IDT_VENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_VENDA");
                    OnIDT_VENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_VENDA;
        partial void OnIDT_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_PRODUTO
        {
            get
            {
                return _IDT_PRODUTO;
            }
            set
            {
                if (_IDT_PRODUTO != value)
                {
                    OnIDT_PRODUTOChanging(value);
                    ReportPropertyChanging("IDT_PRODUTO");
                    _IDT_PRODUTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_PRODUTO");
                    OnIDT_PRODUTOChanged();
                }
            }
        }
        private global::System.Int32 _IDT_PRODUTO;
        partial void OnIDT_PRODUTOChanging(global::System.Int32 value);
        partial void OnIDT_PRODUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QUANTIDADE
        {
            get
            {
                return _QUANTIDADE;
            }
            set
            {
                OnQUANTIDADEChanging(value);
                ReportPropertyChanging("QUANTIDADE");
                _QUANTIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QUANTIDADE");
                OnQUANTIDADEChanged();
            }
        }
        private global::System.Int32 _QUANTIDADE;
        partial void OnQUANTIDADEChanging(global::System.Int32 value);
        partial void OnQUANTIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_UNITARIO
        {
            get
            {
                return _VALOR_UNITARIO;
            }
            set
            {
                OnVALOR_UNITARIOChanging(value);
                ReportPropertyChanging("VALOR_UNITARIO");
                _VALOR_UNITARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_UNITARIO");
                OnVALOR_UNITARIOChanged();
            }
        }
        private global::System.Decimal _VALOR_UNITARIO;
        partial void OnVALOR_UNITARIOChanging(global::System.Decimal value);
        partial void OnVALOR_UNITARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SUBTOTAL
        {
            get
            {
                return _SUBTOTAL;
            }
            set
            {
                OnSUBTOTALChanging(value);
                ReportPropertyChanging("SUBTOTAL");
                _SUBTOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUBTOTAL");
                OnSUBTOTALChanged();
            }
        }
        private Nullable<global::System.Decimal> _SUBTOTAL;
        partial void OnSUBTOTALChanging(Nullable<global::System.Decimal> value);
        partial void OnSUBTOTALChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_ITEM_VENDA_PRODUTO", "PRODUTO")]
        public PRODUTO PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJASenai.FK_ITEM_VENDA_PRODUTO", "PRODUTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJASenai.FK_ITEM_VENDA_PRODUTO", "PRODUTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUTO> PRODUTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUTO>("LOJASenai.FK_ITEM_VENDA_PRODUTO", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUTO>("LOJASenai.FK_ITEM_VENDA_PRODUTO", "PRODUTO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_ITEM_VENDA_VENDA", "VENDA")]
        public VENDA VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("LOJASenai.FK_ITEM_VENDA_VENDA", "VENDA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("LOJASenai.FK_ITEM_VENDA_VENDA", "VENDA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VENDA> VENDAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("LOJASenai.FK_ITEM_VENDA_VENDA", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VENDA>("LOJASenai.FK_ITEM_VENDA_VENDA", "VENDA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="PRODUTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PRODUTO object.
        /// </summary>
        /// <param name="iDT_PRODUTO">Initial value of the IDT_PRODUTO property.</param>
        /// <param name="iDT_CATEGORIA">Initial value of the IDT_CATEGORIA property.</param>
        /// <param name="iDT_FABRICANTE">Initial value of the IDT_FABRICANTE property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="dESCRICAO">Initial value of the DESCRICAO property.</param>
        /// <param name="vALOR">Initial value of the VALOR property.</param>
        /// <param name="dATA_CADASTRO">Initial value of the DATA_CADASTRO property.</param>
        /// <param name="fOTO">Initial value of the FOTO property.</param>
        /// <param name="dESTAQUE">Initial value of the DESTAQUE property.</param>
        public static PRODUTO CreatePRODUTO(global::System.Int32 iDT_PRODUTO, global::System.Int32 iDT_CATEGORIA, global::System.Int32 iDT_FABRICANTE, global::System.String nOME, global::System.String dESCRICAO, global::System.Decimal vALOR, global::System.DateTime dATA_CADASTRO, global::System.String fOTO, global::System.String dESTAQUE)
        {
            PRODUTO pRODUTO = new PRODUTO();
            pRODUTO.IDT_PRODUTO = iDT_PRODUTO;
            pRODUTO.IDT_CATEGORIA = iDT_CATEGORIA;
            pRODUTO.IDT_FABRICANTE = iDT_FABRICANTE;
            pRODUTO.NOME = nOME;
            pRODUTO.DESCRICAO = dESCRICAO;
            pRODUTO.VALOR = vALOR;
            pRODUTO.DATA_CADASTRO = dATA_CADASTRO;
            pRODUTO.FOTO = fOTO;
            pRODUTO.DESTAQUE = dESTAQUE;
            return pRODUTO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_PRODUTO
        {
            get
            {
                return _IDT_PRODUTO;
            }
            set
            {
                if (_IDT_PRODUTO != value)
                {
                    OnIDT_PRODUTOChanging(value);
                    ReportPropertyChanging("IDT_PRODUTO");
                    _IDT_PRODUTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_PRODUTO");
                    OnIDT_PRODUTOChanged();
                }
            }
        }
        private global::System.Int32 _IDT_PRODUTO;
        partial void OnIDT_PRODUTOChanging(global::System.Int32 value);
        partial void OnIDT_PRODUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_CATEGORIA
        {
            get
            {
                return _IDT_CATEGORIA;
            }
            set
            {
                OnIDT_CATEGORIAChanging(value);
                ReportPropertyChanging("IDT_CATEGORIA");
                _IDT_CATEGORIA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_CATEGORIA");
                OnIDT_CATEGORIAChanged();
            }
        }
        private global::System.Int32 _IDT_CATEGORIA;
        partial void OnIDT_CATEGORIAChanging(global::System.Int32 value);
        partial void OnIDT_CATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_FABRICANTE
        {
            get
            {
                return _IDT_FABRICANTE;
            }
            set
            {
                OnIDT_FABRICANTEChanging(value);
                ReportPropertyChanging("IDT_FABRICANTE");
                _IDT_FABRICANTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_FABRICANTE");
                OnIDT_FABRICANTEChanged();
            }
        }
        private global::System.Int32 _IDT_FABRICANTE;
        partial void OnIDT_FABRICANTEChanging(global::System.Int32 value);
        partial void OnIDT_FABRICANTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR
        {
            get
            {
                return _VALOR;
            }
            set
            {
                OnVALORChanging(value);
                ReportPropertyChanging("VALOR");
                _VALOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR");
                OnVALORChanged();
            }
        }
        private global::System.Decimal _VALOR;
        partial void OnVALORChanging(global::System.Decimal value);
        partial void OnVALORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATA_CADASTRO
        {
            get
            {
                return _DATA_CADASTRO;
            }
            set
            {
                OnDATA_CADASTROChanging(value);
                ReportPropertyChanging("DATA_CADASTRO");
                _DATA_CADASTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA_CADASTRO");
                OnDATA_CADASTROChanged();
            }
        }
        private global::System.DateTime _DATA_CADASTRO;
        partial void OnDATA_CADASTROChanging(global::System.DateTime value);
        partial void OnDATA_CADASTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FOTO
        {
            get
            {
                return _FOTO;
            }
            set
            {
                OnFOTOChanging(value);
                ReportPropertyChanging("FOTO");
                _FOTO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FOTO");
                OnFOTOChanged();
            }
        }
        private global::System.String _FOTO;
        partial void OnFOTOChanging(global::System.String value);
        partial void OnFOTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESTAQUE
        {
            get
            {
                return _DESTAQUE;
            }
            set
            {
                OnDESTAQUEChanging(value);
                ReportPropertyChanging("DESTAQUE");
                _DESTAQUE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESTAQUE");
                OnDESTAQUEChanged();
            }
        }
        private global::System.String _DESTAQUE;
        partial void OnDESTAQUEChanging(global::System.String value);
        partial void OnDESTAQUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GARANTIA
        {
            get
            {
                return _GARANTIA;
            }
            set
            {
                OnGARANTIAChanging(value);
                ReportPropertyChanging("GARANTIA");
                _GARANTIA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GARANTIA");
                OnGARANTIAChanged();
            }
        }
        private global::System.String _GARANTIA;
        partial void OnGARANTIAChanging(global::System.String value);
        partial void OnGARANTIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FOTO2
        {
            get
            {
                return _FOTO2;
            }
            set
            {
                OnFOTO2Changing(value);
                ReportPropertyChanging("FOTO2");
                _FOTO2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FOTO2");
                OnFOTO2Changed();
            }
        }
        private global::System.String _FOTO2;
        partial void OnFOTO2Changing(global::System.String value);
        partial void OnFOTO2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FOTO3
        {
            get
            {
                return _FOTO3;
            }
            set
            {
                OnFOTO3Changing(value);
                ReportPropertyChanging("FOTO3");
                _FOTO3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FOTO3");
                OnFOTO3Changed();
            }
        }
        private global::System.String _FOTO3;
        partial void OnFOTO3Changing(global::System.String value);
        partial void OnFOTO3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FOTO4
        {
            get
            {
                return _FOTO4;
            }
            set
            {
                OnFOTO4Changing(value);
                ReportPropertyChanging("FOTO4");
                _FOTO4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FOTO4");
                OnFOTO4Changed();
            }
        }
        private global::System.String _FOTO4;
        partial void OnFOTO4Changing(global::System.String value);
        partial void OnFOTO4Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_PRODUTO_CATEGORIA", "CATEGORIA")]
        public CATEGORIA CATEGORIA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIA>("LOJASenai.FK_PRODUTO_CATEGORIA", "CATEGORIA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIA>("LOJASenai.FK_PRODUTO_CATEGORIA", "CATEGORIA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CATEGORIA> CATEGORIAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIA>("LOJASenai.FK_PRODUTO_CATEGORIA", "CATEGORIA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CATEGORIA>("LOJASenai.FK_PRODUTO_CATEGORIA", "CATEGORIA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_COMENTARIO_PRODUTO", "COMENTARIO")]
        public EntityCollection<COMENTARIO> COMENTARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMENTARIO>("LOJASenai.FK_COMENTARIO_PRODUTO", "COMENTARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMENTARIO>("LOJASenai.FK_COMENTARIO_PRODUTO", "COMENTARIO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_PRODUTO_FABRICANTE", "FABRICANTE")]
        public FABRICANTE FABRICANTE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FABRICANTE>("LOJASenai.FK_PRODUTO_FABRICANTE", "FABRICANTE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FABRICANTE>("LOJASenai.FK_PRODUTO_FABRICANTE", "FABRICANTE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FABRICANTE> FABRICANTEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FABRICANTE>("LOJASenai.FK_PRODUTO_FABRICANTE", "FABRICANTE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FABRICANTE>("LOJASenai.FK_PRODUTO_FABRICANTE", "FABRICANTE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_ITEM_VENDA_PRODUTO", "ITEM_VENDA")]
        public EntityCollection<ITEM_VENDA> ITEM_VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ITEM_VENDA>("LOJASenai.FK_ITEM_VENDA_PRODUTO", "ITEM_VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ITEM_VENDA>("LOJASenai.FK_ITEM_VENDA_PRODUTO", "ITEM_VENDA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="TIPO_VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TIPO_VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TIPO_VENDA object.
        /// </summary>
        /// <param name="iDT_TIPO_VENDA">Initial value of the IDT_TIPO_VENDA property.</param>
        public static TIPO_VENDA CreateTIPO_VENDA(global::System.Int32 iDT_TIPO_VENDA)
        {
            TIPO_VENDA tIPO_VENDA = new TIPO_VENDA();
            tIPO_VENDA.IDT_TIPO_VENDA = iDT_TIPO_VENDA;
            return tIPO_VENDA;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_TIPO_VENDA
        {
            get
            {
                return _IDT_TIPO_VENDA;
            }
            set
            {
                if (_IDT_TIPO_VENDA != value)
                {
                    OnIDT_TIPO_VENDAChanging(value);
                    ReportPropertyChanging("IDT_TIPO_VENDA");
                    _IDT_TIPO_VENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_TIPO_VENDA");
                    OnIDT_TIPO_VENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_TIPO_VENDA;
        partial void OnIDT_TIPO_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_TIPO_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_VENDA_TIPO_VENDA", "VENDA")]
        public EntityCollection<VENDA> VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VENDA>("LOJASenai.FK_VENDA_TIPO_VENDA", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VENDA>("LOJASenai.FK_VENDA_TIPO_VENDA", "VENDA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LOJASenai", Name="VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VENDA object.
        /// </summary>
        /// <param name="iDT_VENDA">Initial value of the IDT_VENDA property.</param>
        /// <param name="iDT_CLIENTE">Initial value of the IDT_CLIENTE property.</param>
        /// <param name="iDT_TIPO_VENDA">Initial value of the IDT_TIPO_VENDA property.</param>
        /// <param name="dATA_VENDA">Initial value of the DATA_VENDA property.</param>
        /// <param name="vALOR_TOTAL">Initial value of the VALOR_TOTAL property.</param>
        /// <param name="sTATUS">Initial value of the STATUS property.</param>
        public static VENDA CreateVENDA(global::System.Int32 iDT_VENDA, global::System.Int32 iDT_CLIENTE, global::System.Int32 iDT_TIPO_VENDA, global::System.DateTime dATA_VENDA, global::System.Decimal vALOR_TOTAL, global::System.String sTATUS)
        {
            VENDA vENDA = new VENDA();
            vENDA.IDT_VENDA = iDT_VENDA;
            vENDA.IDT_CLIENTE = iDT_CLIENTE;
            vENDA.IDT_TIPO_VENDA = iDT_TIPO_VENDA;
            vENDA.DATA_VENDA = dATA_VENDA;
            vENDA.VALOR_TOTAL = vALOR_TOTAL;
            vENDA.STATUS = sTATUS;
            return vENDA;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_VENDA
        {
            get
            {
                return _IDT_VENDA;
            }
            set
            {
                if (_IDT_VENDA != value)
                {
                    OnIDT_VENDAChanging(value);
                    ReportPropertyChanging("IDT_VENDA");
                    _IDT_VENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDT_VENDA");
                    OnIDT_VENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDT_VENDA;
        partial void OnIDT_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_CLIENTE
        {
            get
            {
                return _IDT_CLIENTE;
            }
            set
            {
                OnIDT_CLIENTEChanging(value);
                ReportPropertyChanging("IDT_CLIENTE");
                _IDT_CLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_CLIENTE");
                OnIDT_CLIENTEChanged();
            }
        }
        private global::System.Int32 _IDT_CLIENTE;
        partial void OnIDT_CLIENTEChanging(global::System.Int32 value);
        partial void OnIDT_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDT_TIPO_VENDA
        {
            get
            {
                return _IDT_TIPO_VENDA;
            }
            set
            {
                OnIDT_TIPO_VENDAChanging(value);
                ReportPropertyChanging("IDT_TIPO_VENDA");
                _IDT_TIPO_VENDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDT_TIPO_VENDA");
                OnIDT_TIPO_VENDAChanged();
            }
        }
        private global::System.Int32 _IDT_TIPO_VENDA;
        partial void OnIDT_TIPO_VENDAChanging(global::System.Int32 value);
        partial void OnIDT_TIPO_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATA_VENDA
        {
            get
            {
                return _DATA_VENDA;
            }
            set
            {
                OnDATA_VENDAChanging(value);
                ReportPropertyChanging("DATA_VENDA");
                _DATA_VENDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA_VENDA");
                OnDATA_VENDAChanged();
            }
        }
        private global::System.DateTime _DATA_VENDA;
        partial void OnDATA_VENDAChanging(global::System.DateTime value);
        partial void OnDATA_VENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_TOTAL
        {
            get
            {
                return _VALOR_TOTAL;
            }
            set
            {
                OnVALOR_TOTALChanging(value);
                ReportPropertyChanging("VALOR_TOTAL");
                _VALOR_TOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_TOTAL");
                OnVALOR_TOTALChanged();
            }
        }
        private global::System.Decimal _VALOR_TOTAL;
        partial void OnVALOR_TOTALChanging(global::System.Decimal value);
        partial void OnVALOR_TOTALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private global::System.String _STATUS;
        partial void OnSTATUSChanging(global::System.String value);
        partial void OnSTATUSChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_VENDA_CLIENTE", "CLIENTE")]
        public CLIENTE CLIENTE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("LOJASenai.FK_VENDA_CLIENTE", "CLIENTE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("LOJASenai.FK_VENDA_CLIENTE", "CLIENTE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTE> CLIENTEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("LOJASenai.FK_VENDA_CLIENTE", "CLIENTE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENTE>("LOJASenai.FK_VENDA_CLIENTE", "CLIENTE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_ITEM_VENDA_VENDA", "ITEM_VENDA")]
        public EntityCollection<ITEM_VENDA> ITEM_VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ITEM_VENDA>("LOJASenai.FK_ITEM_VENDA_VENDA", "ITEM_VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ITEM_VENDA>("LOJASenai.FK_ITEM_VENDA_VENDA", "ITEM_VENDA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LOJASenai", "FK_VENDA_TIPO_VENDA", "TIPO_VENDA")]
        public TIPO_VENDA TIPO_VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_VENDA>("LOJASenai.FK_VENDA_TIPO_VENDA", "TIPO_VENDA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_VENDA>("LOJASenai.FK_VENDA_TIPO_VENDA", "TIPO_VENDA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TIPO_VENDA> TIPO_VENDAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_VENDA>("LOJASenai.FK_VENDA_TIPO_VENDA", "TIPO_VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TIPO_VENDA>("LOJASenai.FK_VENDA_TIPO_VENDA", "TIPO_VENDA", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
